wandb_version: 1

num_classes:
  desc: null
  value: 200
model_name:
  desc: null
  value: ''
lr_milestones:
  desc: null
  value:
  - 60
  - 100
lr_decay_rate:
  desc: null
  value: 0.1
input_size:
  desc: null
  value: 448
root:
  desc: null
  value: ./datasets/FGVC-aircraft
end_epoch:
  desc: null
  value: 200
save_interval:
  desc: null
  value: 5
init_lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 6
CUDA_VISIBLE_DEVICES:
  desc: null
  value: '0'
weight_decay:
  desc: null
  value: 0.0001
proposalN:
  desc: null
  value: 7
set:
  desc: null
  value: Aircraft
channels:
  desc: null
  value: 2048
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716940456
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 16
      - 23
      - 24
      - 61
      4: 3.7.16
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
